@extends('landingpage.layouts.master')

@section('content')
	<section class="services py-5" id="home">
		<div class="container py-md-5 py-3">
			<div class="row text-justify">
				<div class="col-1"></div>
				<div class="col-10">
					<h2 class="mb-4 heading text-center">Terms of <span>Service</span></h2>
					<p class="mt-4">Please read this Agreement carefully before using the Services. By using the website http://Peasisoft.com (the &quot;Site&quot;), and applications, features and other content (collectively, the &quot;Services&quot;) offered by Peasisoft, Inc. (&quot;Peasisoft&quot;), you signify your assent to become bound by the terms and conditions of this Agreement. If you do not agree to all the terms and conditions of this Agreement, you do not have any right to use the Services.</p>

					<p class="mt-4">The Services, owned and operated by Peasisoft, collect user and usage data to enable website and application owners to send e-mail messages efficiently to consumers based on their behavior. This Agreement applies to all users of the Services. Your use of the Services is an acknowledgment that you understand and agree to be bound by this Agreement, any fees applicable to you, any additional guidelines, Peasisoft's Privacy Policy and Anti-Spam Policy, and any future modifications of this Agreement.</p>

					<p class="mt-4">The Services are accessed by you (&quot;User&quot; or &quot;you&quot;) under the following terms and conditions:</p>

					<p class="mt-4">1. ACCESS TO THE SERVICES</p>

					<p class="mt-4">Subject to the terms and conditions of this Agreement, Peasisoft may provide the Services, which are selected by you, solely for your own use, and not for the use or benefit of any third party. Services shall include, but not be limited to, the offering of any materials displayed or performed on the Site and related features (including, but not limited to text, data, software, graphics, photographs, images, illustrations, audio clips and video clips, also known as the &quot;Content&quot;). Peasisoft may change, suspend or discontinue the Services for any reason, at any time, including the availability of any feature or Content. Peasisoft may also restrict your access to parts or all of the Services without notice or liability. Peasisoft may modify this Agreement at any time by posting a notice on the Services, or by sending you a notice via e-mail or postal mail. You shall be responsible for reviewing and becoming familiar with any such modifications. Your use of the Services following such notification constitutes your acceptance of the terms and conditions of this Agreement as modified. If at any time you do not agree to these terms and conditions, you must terminate your use of the Services. You will still remain liable for any obligations incurred or charges accrued on or before the date of termination.</p>

					<p class="mt-4">You certify to Peasisoft that if you are an individual (i.e., not a corporation) you are at least 18 years of age. You also certify that you are legally permitted to use the Services and access the Site. If you are entering into this Agreement on behalf of a company or other legal entity, you represent and warrant that you have the authority to bind such entity to this agreement, in which case the terms &quot;you&quot; or &quot;your&quot; shall refer to such entity. This Agreement is void where prohibited by law, and the right to use the Services is revoked in such jurisdictions.</p>

					<p class="mt-4">Peasisoft will use reasonable efforts to ensure that the Services are available twenty-four hours a day, seven days a week. However, there will be occasions when the Services will be interrupted for maintenance, upgrades and emergency repairs or due to failure of telecommunications links and equipment. Every reasonable step will be taken by Peasisoft to minimize such disruption where it is within Peasisoft's reasonable control. Peasisoft will not be liable in any event to you or any other party for any suspension, modification, discontinuance or lack of availability of the Site, the Services, your Customer Data or Results (as defined herein) or other content.</p>

					<p class="mt-4">2. CONTENT</p>

					<p class="mt-4">You shall not store any significant portion of the Content in any form. Copying or storing of any Content for other than personal, noncommercial use is expressly prohibited without prior written permission from Peasisoft, or from the copyright holder identified in such Content's copyright notice. All trademarks, service marks, and trade names which appear on the Services are proprietary to Peasisoft or third parties. You shall abide by all copyright notices and restrictions contained in any Content accessed through the Services.</p>

					<p class="mt-4">The Services are protected by copyright as a collective work and/or compilation, pursuant to U.S. and other copyright laws. Subject to the terms and conditions of this Agreement, Peasisoft grants you a nonexclusive, nontransferable right and license (without right to sublicense) to access and use the Services, solely for your internal business purposes. You may not (except as provided in this Section of this Agreement) modify, publish, transmit, participate in the transfer or sale of, reproduce, create derivative works based on, distribute, perform, display, or in any way exploit, any of the Content, software, materials, or Services in whole or in part.</p>

					<p class="mt-4">3. CUSTOMER DATA</p>

					<p class="mt-4">You acknowledge and agree that if you provide data regarding your end users or e-mail campaigns to Peasisoft in connection with your use of the Services (&quot;Customer Data&quot;), you hereby do and shall grant Peasisoft a non-exclusive, worldwide, royalty-free, transferable right to use, modify, reproduce, and display such Customer Data (including all related intellectual property rights) to (i) provide the Services and (ii) improve the Services' ability to deliver web and application analytics services to you. You warrant, represent and agree that you have the right to grant Peasisoft the rights set forth above. You represent and warrant that you own all right, title and interest, or possess sufficient license rights, in and to the Customer Data as may be necessary to permit the use contemplated under this Agreement. You bear all responsibility and liability for the accuracy, completeness, quality, integrity, legality, reliability, appropriateness, and intellectual property ownership or right of the Customer Data and Peasisoft's access, possession and use as permitted herein. You represent, warrant and agree that you will not contribute any Customer Data that (a) infringes or violates any copyright or trademark or trade secret of another party, (b) infringes any intellectual property right or the privacy or publicity rights of another, &copy; is libelous, defamatory, obscene, pornographic, harassing, hateful, offensive or otherwise violates any law or right of any third party, (d) contains a virus, trojan horse, worm, or other computer programming routine or engine intended to detrimentally interfere with any system, data or information, or (e) causes damage to the systems of Peasisoft or its customers in any way.</p>

					<p class="mt-4">If you disclose Customer Data which includes personally identifiable information (&quot;PII&quot;) of end users of your site or application (&quot;Customer Site&quot;) to Peasisoft, you represent and warrant that: (i) you comply with all applicable laws relating to the collection, use and disclosure of PII on your Customer Site; (ii) you have posted and maintain a privacy policy on your Customer Site, which clearly and conspicuously discloses that: (a) you use third-party service providers to provide services to you in connection with your operation of your Customer Site, including the collection and tracking of certain data and information regarding the characteristics and activities of visitors to such Customer Site; and (b) you may disclose end user PII to certain such third-party service providers in connection with their provision of services to you; and (iii) you have made all required notifications and obtained all required consents and authorizations from your end users relating to the disclosure of end user PII to a third party service provider like Peasisoft. You further acknowledge and agree that your indemnity obligation under the &quot;Indemnity&quot; section below applies to your disclosure of end user PII under this Agreement.</p>

					<p class="mt-4">Peasisoft reserves the right to remove any Customer Data from the Site and the Services at any time, for any reason or for no reason at all. Peasisoft may, but is not obligated to, monitor Customer Data and remove any content or prohibit any use of the Services, including by refusing to send e-mail to your end users, if Peasisoft believes in its sole discretion such content or use may be (or is alleged to be) in violation of these Terms of Service or any applicable laws or may impact delivery. All information transmitted through the Services is the sole responsibility of the party from whom such information originated. Peasisoft does not assume liability for any Customer Data. You are responsible for all Customer Data submitted under your account, including Customer Data contributed by a third party under your account. Any feedback relating to the Services (&quot;Feedback&quot;) submitted to Peasisoft shall become the property of Peasisoft. Peasisoft will not be required to treat any Feedback as confidential, and will not be liable for any ideas or incur any liability as a result of any similarities that may appear in our future Services, or operations.</p>

					<p class="mt-4">4. RESULTS</p>

					<p class="mt-4">Unless otherwise agreed by the parties and subject to Peasisoft's rights set forth in this Section 4, you shall own all right, title and interest (including all intellectual property and other proprietary rights) in and to all data developed using your Customer Data during the performance of the Services and delivered to you by Peasisoft (&quot;Results&quot;). Results are works made for hire to the extent allowed by law, and Peasisoft makes all assignments to you necessary to accomplish the foregoing ownership. You hereby grant Peasisoft a limited, non-exclusive right (i) to disclose your Results to Peasisoft's employees and agents solely as required for them to provide Peasisoft with their products and services, and (ii) to disclose your Results to comply with court order, law, or direction by a governmental or regulatory agency (in which event, Peasisoft will use reasonable efforts to provide prior written notice to you of such disclosure and the opportunity to object to such disclosure or to seek confidential treatment of such data), and (iii) to use your Results to operate, manage, and maintain the Services, and to improve the Services' ability to deliver web and application analytics services to you. Peasisoft may compile and analyze Results and prepare reports and other work product using the aggregate Results compiled from you and other customers. Notwithstanding anything in this Agreement, Peasisoft shall have exclusive ownership rights to, and the exclusive right to use, such compiled Results for any purpose, including, but not limited to advertising, marketing, and improvement of the Services. Peasisoft shall not distribute compiled Results in a manner that identifies you without first obtaining your prior written consent.</p>

					<p class="mt-4">Peasisoft has no obligation to store any Results after delivery of such Results to you. Peasisoft reserves the right to withhold, remove or discard Results without notice for any breach of this Agreement by you, including, without limitation, your non-payment of fees due hereunder. Upon termination of this Agreement for your breach, Peasisoft shall have no obligation to maintain or forward any Results to you.</p>

					<p class="mt-4">5. RESTRICTIONS</p>

					<p class="mt-4">You are responsible for all of your activity in connection with the Services. You may not post or transmit, or cause to be posted or transmitted, any communication designed or intended to obtain password, account, or private information from any Peasisoft user. Peasisoft will not be liable for any failures in the Services or other problems which are related to your Customer Data or any equipment or service outside of Peasisoft's facilities or control. You shall not use any part of the Site or Services to violate the security of any computer network, crack passwords or security encryption codes, transfer or store material that is deemed threatening or obscene, or engage in any kind of illegal activity. You will not run Maillist, Listserv, any form of auto-responder, or spam on the Site or through the Services. You will use the Services only in compliance with all applicable laws (including but not limited to policies and laws related to spamming, privacy, intellectual property, consumer and child protection, obscenity, or defamation). You represent, warrant and covenant that your use of the Services shall at all times comply with Peasisoft's Anti-Spam Policy, as may be amended by Peasisoft from time to time, and you will not access or use third party mailing lists in connection with preparing or distributing e-mail through the Services.</p>

					<p class="mt-4">6. WARRANTY DISCLAIMER</p>

					<p class="mt-4">Peasisoft has no special relationship with or fiduciary duty to you. You acknowledge that Peasisoft has no control over, and no duty to take any action regarding: which users gain access to the Services; what Results you may obtain via the Services; what effects the Content may have on you; how you may interpret or use the Results; or what actions you may take as a result of having been exposed to the Content. You release Peasisoft from all liability for your having acquired or not acquired Content and Results through the Services. Peasisoft does not manage or control any business or individual that you may interact with through the Services, and Peasisoft accepts no responsibility or liability for any act or omission by such entity. You hereby waive any and all legal or equitable rights or remedies you have or may have against Peasisoft with respect to acts and omissions by such entities.</p>

					<p class="mt-4">The Services may contain, or direct you to sites containing, information that some people may find offensive or inappropriate. Peasisoft makes no representations concerning any content contained in or accessed through the Services, and Peasisoft will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Services. THE SERVICES, CONTENT, RESULTS, SITE AND ANY SOFTWARE ARE PROVIDED ON AN &quot;AS IS&quot; BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE OR NON-INFRINGEMENT. SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.</p>

					<p class="mt-4">TO THE FULLEST EXTENT ALLOWED BY LAW, Peasisoft DISCLAIMS ANY LIABILITY OR RESPONSIBILITY FOR THE ACCURACY, RELIABILITY, AVAILABILITY, COMPLETENESS, LEGALITY OR OPERABILITY OF THE MATERIAL PROVIDED THROUGH THE SERVICES. BY USING THE SERVICES, YOU ACKNOWLEDGE THAT Peasisoft IS NOT RESPONSIBLE OR LIABLE FOR ANY HARM RESULTING FROM (1) USE OF THE SERVICES; (2) DOWNLOADING INFORMATION CONTAINED ON THE SERVICES; (3) UNAUTHORIZED DISCLOSURE OF IMAGES, INFORMATION OR DATA THROUGH THE SERVICES; AND (4) THE INABILITY TO ACCESS OR RETRIEVE ANY RESULTS FROM THE SERVICES, INCLUDING, WITHOUT LIMITATION, HARM CAUSED BY VIRUSES OR ANY SIMILAR DESTRUCTIVE PROGRAM.</p>

					<p class="mt-4">7. THIRD PARTY SITES AND SERVICES</p>

					<p class="mt-4">Users of Peasisoft may gain access from the Services to third party sites on the Internet. Third party sites or services are not within the supervision or control of Peasisoft. Peasisoft makes no representations or warranties about any third party site or resource, and does not endorse the products or services offered by third parties. Peasisoft disclaims all responsibility and liability for content on third party websites. You hereby irrevocably waive any claim against Peasisoft with respect to third party content. Third party providers of ancillary services may require your agreement to additional or different license or other terms prior to your use or access of their sites or services. Any such agreement shall not in any way modify your Agreement here with Peasisoft.</p>

					<p class="mt-4">8. REGISTRATION AND SECURITY</p>

					<p class="mt-4">As a condition to using Services, you may be required to supply Peasisoft with certain registration information. You shall provide Peasisoft with accurate, complete, and updated registration information. Failure to do so shall constitute a breach of this Agreement, which may result in termination of your access to and use of the Services. You shall never use another User's account or registration information, for Peasisoft's or any third party services you access through Peasisoft, without permission. Peasisoft reserves the right to refuse registration of or cancel an account in its discretion. You shall be responsible for maintaining the confidentiality of your Peasisoft password and for all activity of any person who accesses the Services using your password.</p>

					<p class="mt-4">You irrevocably authorize Peasisoft to disclose your personally identifiable information or the personally identifiable information of your end users collected by Peasisoft at the request of any state, federal or other governmental agency or in response to any judicial process (including, without limitation, a subpoena).</p>

					<p class="mt-4">9. INDEMNITY</p>

					<p class="mt-4">You will indemnify and hold Peasisoft, its directors, officers, employees, agents, and representatives harmless, including costs and attorneys' fees, from any claim or demand made by any third party due to or arising out of your access to or use of the Services, your violation of this Agreement, or your infringement, or the infringement by any third party using your registration information, of any intellectual property, or other right of any person or entity, including but not limited to any third party claims relating to your disclosure of end personally identifiable information of your end users to Peasisoft.</p>

					<p class="mt-4">10. LIMITATION OF LIABILITY</p>

					<p class="mt-4">IN NO EVENT SHALL Peasisoft, ITS DIRECTORS, OFFICERS, SHAREHOLDERS, EMPLOYEES, MEMBERS, AGENTS AND REPRESENTATIVES BE LIABLE WITH RESPECT TO THE SERVICES FOR (A) ANY INDIRECT, INCIDENTAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND; (B) DAMAGES FOR LOSS OF USE, PROFITS, DATA, IMAGES, CUSTOMER DATA OR OTHER INTANGIBLES; &copy; DAMAGES FOR UNAUTHORIZED USE, NON-PERFORMANCE OF THE SITE, ERRORS OR OMISSIONS; OR (D) DAMAGES RELATED TO DOWNLOADING OR USING RESULTS. Peasisoft'S LIABILITY UNDER THIS AGREEMENT SHALL BE LIMITED TO THE AMOUNT PAID BY YOU, IF ANY, FOR ACCESSING THE SERVICES DURING THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE DAY THE ACT OR OMISSION OCCURRED THAT GAVE RISE TO YOUR CLAIM. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATIONS AND EXCLUSIONS MAY NOT APPLY TO YOU.</p>

					<p class="mt-4">11. TERMINATION; FEES</p>

					<p class="mt-4">Either party may terminate the Services at any time by notifying the other party by any means. Peasisoft may also terminate or suspend any and all Services immediately, without prior notice or liability, if you breach any of the terms or conditions of this Agreement. Any fees paid hereunder are non-refundable. Upon any such termination, your right to use the Services and access Results will immediately cease. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnification obligations, and limitations of liability.</p>

					<p class="mt-4">Peasisoft may charge a monthly subscription fee for use of the Services. In the event you purchase paid Services, your credit card will be charged based on our policy and the policies of our partners' platforms such as: Shopify, WooCommerce, BigCommerce, Magento, Prestashop, etc.. You may cancel your Peasisoft subscription at any time, but once you have been charged a subscription fee, there are no refunds, partial or in full, for that fee.</p>

					<p class="mt-4">12. PRIVACY</p>

					<p class="mt-4">Please review our Privacy Policy, which governs the use of personal information by Peasisoft and to which you agree to be bound as a user of the Services.</p>

					<p class="mt-4">13. DISPUTE RESOLUTION</p>

					<p class="mt-4">A printed version of this Agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. Any cause of action arising out of or related to the Services must commence within one (1) year after the cause of action arose; otherwise, such cause of action is permanently barred.</p>

					<p class="mt-4">This Agreement shall be governed by and construed in accordance with the laws of Singapore. Any dispute arising from or relating to the subject matter of this Agreement shall be finally settled by the state and federal courts located in Singapore. Use of the Services is not authorized in any jurisdiction that does not give effect to all provisions of this Agreement, including without limitation, this section.</p>

					<p class="mt-4">14. MISCELLANEOUS</p>

					<p class="mt-4">The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder. Peasisoft shall not be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond Peasisoft's reasonable control, including, without limitation, mechanical, electronic or communications failure or degradation. If any provision of this Agreement is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable. This Agreement is not assignable, transferable or sublicensable by you except with Peasisoft's prior written consent. Peasisoft may transfer, assign or delegate this Agreement and any or all of its rights and obligations without consent. Peasisoft may publicly disclose in writing that customers who purchase paid Services are customers and may use their trademarks, service marks or trade name solely in connection with such disclosures. This Agreement (including the Privacy Policy and Anti-Spam Policy) is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement. No agency, partnership, joint venture, or employment is created as a result of this Agreement and you do not have any authority to bind Peasisoft in any respect whatsoever. Any notice that is required or permitted by this Agreement shall be in writing and shall be deemed effective upon receipt, when sent by confirmed e-mail to hey@Peasisoft.com.</p>

					<p class="mt-4">Copyright 2019 Peasisoft, Inc. All rights reserved.</p>
				</div>
			</div>
		</div>
	</section>
@endsection
