let constants = {
    COURSE_DANG_TUYEN: 1,
    COURSE_NGUNG_TUYEN: 2,
    COURSE_KET_THUC: 3,

    EXAM_OPEN: 1,
    EXAM_FINISHED: 2,
    EXAM_UPDATED_SCORE: 3,

    TYPE_LINE: 1,
    TYPE_CIRCLE: 2,

    PROGRAM_GO: 'G0',
    PROGRAM_G1: 'G1',
    PROGRAM_G2: 'G2',
    PROGRAM_G3: 'G3',

    TICKET_COMPLETED: 1,
    TICKET_PENDING: 0,
    TICKET_BLOCKED: 99,

    CENTRAL_TYPE : 0,
    OUTSIDE_CENTRAL_TYPE : 1,
    PERSONAL_TYPE : 2,

    TRONG_HINH_TYPE : 1,
    DUONG_TRUONG_TYPE : 2,
    FOUR_HOUR_TYPE : 3,
    ONE_HOUR_TYPE : 4,

    TRONG_GIO_HANH_CHINH_TYPE : 1,
    NGOAI_GIO_HANH_CHINH_TYPE : 2,
    BUOI_SANG_CHIEU_TYPE : 3,
    BUOI_TOI_TYPE : 4,

    CHECKED : 1,
    UNCHECKED : 2,
}

export default constants;
