<?php

return [
    'dashboard' => [
        'name' => 'dashboard',
        'text' => 'Dashboard',
        'icon' => 'fa fa-dashboard',
        'router' => '/admin/dashboard',
        'order' => 0,
        'tag' => '',
        'authorize' => [],
    ],
    'Offers' => [
        'name' => 'Offers',
        'text' => 'Offers',
        'icon' => 'fa fa-gift',
        'router' => '#',
        'order' => 2,
        'authorize' => [],
        'tag' => "",
        'sub'   => [
            'student' => [
                'name' => 'student',
                'text' => 'Danh sách học viên',
                'icon' => 'fa fa-users',
                'router' => '/admin/student/students',
                'order' => 1,
                'authorize' => [],
            ],
            'dang-ky-hoc' => [
                'name' => 'dang-ky-hoc',
                'text' => 'Đăng ký học',
                'icon' => 'fa fa-user',
                'router' => '/admin/student/create',
                'order' => 1,
                'authorize' => [],
            ],
            'group-create' => [
                'name' => 'group-create',
                'text' => 'Đăng kí nhóm',
                'icon' => 'fa fa-user-plus',
                'router' => '/admin/group/create',
                'order' => 1,
                'authorize' => [],
            ],
            'group' => [
                'name' => 'group',
                'text' => 'Danh sách nhóm',
                'icon' => 'fa fa-users',
                'router' => '/admin/group/groups',
                'order' => 1,
                'authorize' => [],
            ],
            'practice' => [
                'name' => 'practice',
                'text' => 'Lịch thực hành',
                'icon' => 'fa fa-users',
                'router' => '/admin/practice/practices',
                'order' => 1,
                'authorize' => [],
            ]

        ]
    ],
    'Reports' => [
        'name' => 'Reports',
        'text' => 'Reports',
        'icon' => 'fa fa-bar-chart',
        'router' => '/admin/teacher/',
        'order' => 1,
        'tag' => "MAIN MENU",
        'size' => 20,
        'authorize' => [],
    ],
    'template' => [
        'name' => 'template',
        'text' => 'Template hub',
        'icon' => 'fa fa-files-o',
        'router' => '/admin/teacher/teachers',
        'order' => 2,
        'tag' => "",
        'authorize' => [],
    ],
    'ticket' => [
        'name' => 'ticket',
        'text' => 'My tickets',
        'icon' => 'fa fa-ticket',
        'router' => '/admin/user/users',
        'tag' => "HELP CENTRER",
        'size' => 20,
        'order' => 3,
        'authorize' => [],
    ],
    'tutorial' => [
        'name' => 'Tutorials',
        'text' => 'Tutorials',
        'icon' => 'fa fa-camera',
        'router' => '/admin/account/profile',
        'order' => 4,
        'tag' => "",
        'authorize' => [],
    ],
    'faq' => [
        'name' => 'faq',
        'text' => 'FAQs',
        'icon' => 'fa fa-question-circle',
        'router' => '/admin/class/classes',
        'order' => 5,
        'tag' => "",
        'authorize' => [],
    ],
    'program' => [
        'name' => 'program',
        'text' => 'Feature requests',
        'icon' => 'fa fa-star',
        'router' => '/admin/program/programs',
        'order' => 6,
        'tag' => "",
        'authorize' => [],
    ],
    'account-setting' => [
        'size' => 40,
        'name' => 'account-setting',
        'text' => 'Account setting',
        'icon' => 'fa fa-gear fa-spin',
        'router' => '/admin/program/programs',
        'tag' => "ACCOUNT SETTING",
        'order' => 7,
        'authorize' => [],
    ],
];
